### PR TITLE
[MM-29970] Add e2e test for pluginInstallURLCmdF

### PR DESCRIPTION
**Pull request by wijayaerick**
#### Summary

Added e2e test for pluginInstallURLCmdF.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16075

Jira: https://mattermost.atlassian.net/browse/MM-29970

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
Great work @wijayaerick! Thanks a lot for the contribution!!

**Review by ashishbhate — APPROVED** [review]
Apologies for the delay in getting to this. LGTM! Thanks @wijayaerick

**Review by lindy65 — APPROVED** [review]
Thanks @wijayaerick @mgdelacroix - looks good to me 👍

**Comment by hanzei** [comment]
Finally CI passed :tada: Sorry for the long time it took to merge your PR. Thanks for submitting it!

**Pull request merged**
