### PR TITLE
DOC: Moved Compile and Developer sections below "usage"

### PR DESCRIPTION
**Pull request by aaronrothschild**
It threw me off when I didn't see usage section higher.  1/5 on this change.

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
Makes sense, LGTM! :+1:

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by hanzei** [comment]
@mgdelacroix Can we merge this?

**Comment by mgdelacroix** [comment]
Yup, merged!

**Pull request merged**
