### PR TITLE
Add e2e tests for searchChannelCmdF

### PR DESCRIPTION
**Pull request by shihanng**
Close https://github.com/mattermost/mattermost-server/issues/15811

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM!

**Review by mgdelacroix — APPROVED** [review]
LGTM! Thanks for your contribution @shihanng!! :confetti_ball:

**Review by lindy65 — APPROVED** [review]
Thanks @shihanng @mgdelacroix - looks good to me 👍

**Comment by shihanng** [comment]
Updated branch to resolve conflict.

**Comment by hanzei** [comment]
Thanks for the contribution @shihanng :rocket:

**Pull request merged**
