### PR TITLE
[MM-21225] commands/bot: enable creating access token after a bot creation

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
commands/bot: enable creating access token after a bot creation by adding a new flag `--with-token`. It simply runs the `generateTokenForAUserCmdF` after the `botCreateCmdF`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21225

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Nice :+1: Does this need e2e test changes/additions?

**Comment by isacikgoz** [comment]
@streamer45 e2e tests run the command handlers. This implementation just attaches another handler after the `botCreateCmdF` so it's not necessary imo, but I also wonder what @mgdelacroix thinks about it.

**Review by mgdelacroix — COMMENTED** [review]
Hum... I'm a bit hesitant on using `PostRun` for this, as it is kinda splitting the logic in two places.

The way I see it, `Pre` and `Post` are used for generic processes that are dissociated from the main logic of the command (initialization and teardown mainly), and the token creation feels more like an extra step of the command.

I'm not fixed to this idea, tho, like 3/5. Thoughts?

**Comment by mgdelacroix** [comment]
> I also wonder what @mgdelacroix thinks about it.

Based on my previous comment, I think we should only test for the call happening if the flag is received, as the logic is tested in the handler itself. I'd add just a unit test for this

**Comment by isacikgoz** [comment]
> Hum... I'm a bit hesitant on using `PostRun` for this, as it is kinda splitting the logic in two places.
> 
> The way I see it, `Pre` and `Post` are used for generic processes that are dissociated from the main logic of the command (initialization and teardown mainly), and the token creation feels more like an extra step of the command.
> 
> I'm not fixed to this idea, tho, like 3/5. Thoughts?

I think you're right, I didn't think this way TBH. As this is not a mandatory post action it will be better to put this inside the handler.

**Review by mgdelacroix — APPROVED** [review]
Awesome, thanks for applying the changes!! :rocket: LGTM!

**Review by lindy65 — APPROVED** [review]
Hi @isacikgoz - thanks, this will be tested after merge 👍 

When you do an E2E test for this command, please link the following Zephyr test code in the s.Run line:
MM-T3941 

Thanks! :)

**Pull request merged**
