### PR TITLE
[MM-36562] Implement `extract` command

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR implements a new `extract` command to run the file content extraction process through a job.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-36562

#### Releated PR

https://github.com/mattermost/mattermost-server/pull/18022

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
Awesome 👍

**Comment by furqanmlk** [comment]
@streamer45 I am getting `unknown command "extract" for "mmctl" ` error
I got Server PR too

image

**Review by furqanmlk — COMMENTED** [review]
`unknown command "extract" for "mmctl"`

**Comment by streamer45** [comment]
@furqanmlk 

Sounds like you may be using an older version. You can run `mmctl version` to find out.
By the way, to test the PR you could also checkout the git branch and run `go run mmctl.go` instead of installing the binary.

**Review by furqanmlk — APPROVED** [review]
Updated in server PR

**Pull request merged**
