### PR TITLE
[MM-29807] Add e2e test for botEnableCmdF

### PR DESCRIPTION
**Pull request by wijayaerick**
#### Summary

Added e2e test for botEnableCmdF.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16003

JIRA: https://mattermost.atlassian.net/browse/MM-29807

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM!

**Review by mgdelacroix — APPROVED** [review]
Awesome work @wijayaerick, thanks for the contribution!! :sparkles:

**Comment by hanzei** [comment]
Thank you for the PR @wijayaerick :tada:

**Pull request merged**
