### PR TITLE
Use newer golangci-lint version

### PR DESCRIPTION
**Pull request by metanerd**

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Thanks :+1:

**Comment by streamer45** [comment]
Not sure why this is consistently failing several tests. @mgdelacroix do you have a clue?

**Comment by mgdelacroix** [comment]
@streamer45 weird behavior indeed, the image is constrained to the `lint` job, so it should not affect to the `test` one, which is actually passing in `master` :thinking:

**Comment by streamer45** [comment]
> @streamer45 weird behavior indeed, the image is constrained to the `lint` job, so it should not affect to the `test` one, which is actually passing in `master`

Oh well, this is getting merged into my PR not into master. Had to deal with a few unrelated changes (breaking of client API due to collapsed threads and Golang version bump) so probably something got broken. I can merge this and try to deal with the issues there I guess.

**Comment by mgdelacroix** [comment]
Totally missed the fact that this was not being migrated on `master` :grimacing: makes sense to deal with the issue in your branch then :)

**Pull request merged**
