### PR TITLE
[MM-47826] Review convertUserToBot function to return an error in case of a failure (#21460)

### PR DESCRIPTION
**Pull request by akadir**
#### Summary

Return error from the convertUserToBot if the function fails.

#### Ticket Link

Fixes [#21460](https://github.com/mattermost/mattermost-server/issues/21460)

JIRA: https://mattermost.atlassian.net/browse/MM-47826

### CODE REVIEW

**Comment by isacikgoz** [comment]
@akadir Let us know if you need any assistance regarding to linter. The error on tests seems to be a trivial one, you just need to give exact error message, or alternatively you can use `Contains` method.

**Comment by isacikgoz** [comment]
And ask for a review once you feel ready :)

**Comment by akadir** [comment]
Sorry for the delay @isacikgoz 
I have updated the related tests for this and this(#585) PRs. 
Could you please check when you are available?

**Comment by hanzei** [comment]
Thank you for your contribution. :+1:  `mmctl` has been moved into https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl.  Please resubmit your PR to https://github.com/mattermost/mattermost.

**Pull request closed without merging**
