### PR TITLE
[MM-50414] Allow admins to change own email

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
If the current user is the same as the target one, ask for the password needed from the API to change the email.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50414

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
Feels wrong that you can update other's emails but to update your own you need to specify your password.

**Comment by kostaspt** [comment]
@ harshilsharma63 I had the same thought while doing the task, but I guess the point is that if you change your email, you could be locked out of your account while you can undo the change you've made to others.

**Review by furqanmlk — COMMENTED** [review]
@kostaspt, I am still getting the same error.

image

**Comment by kostaspt** [comment]
@furqanmlk Weird... Maybe logged in with a different account? I tried with the same creds now:

image

**Comment by kostaspt** [comment]
@furqanmlk Maybe we should revisit this at some point to merge?

**Comment by Willyfrog** [comment]
@furqanmlk do you need any help testing this? 

@kostaspt maybe a quick call might unblock this?

**Comment by furqanmlk** [comment]
> @furqanmlk do you need any help testing this?
> 
> @kostaspt maybe a quick call might unblock this?

Sorry it was not re-assigned to me, I missed the from my list.
Let me re-test now

**Comment by furqanmlk** [comment]
@kostaspt 
It works fine if I log in using a username and password, but it fails when I log in using an access token.

image


image

**Comment by hanzei** [comment]
Thank you for your contribution. :+1:  `mmctl` has been moved into https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl.  Please resubmit your PR to https://github.com/mattermost/mattermost.

**Pull request closed without merging**
