### PR TITLE
[MM-29732] Added e2e tests to the "configSetCmdF" command

### PR DESCRIPTION
**Pull request by SezalAgrawal**
#### Summary

Added e2e tests to the "configSetCmdF" mmctl command

#### Ticket Link

Fixes: mattermost/mattermost-server#15980

JIRA: https://mattermost.atlassian.net/browse/MM-29732

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by mgdelacroix — APPROVED** [review]
LGTM! Thanks a lot for the PR @SezalAgrawal!!!

**Review by lindy65 — APPROVED** [review]
Thanks @SezalAgrawal @mgdelacroix - looks good to me 👍

**Comment by hanzei** [comment]
Thanks @SezalAgrawal :tada:

**Pull request merged**
