### PR TITLE
MM-41184: Throw a warning if config migrate wasn't run in local mode

### PR DESCRIPTION
**Pull request by agnivade**
Also added a note in the docs.

### CODE REVIEW

**Comment by isacikgoz** [comment]
@agnivade it seems like the tests need to be updated as well.

**Comment by agnivade** [comment]
All good now, but why are some checks still pending? :thinking: Is there something else I need to do?

**Comment by isacikgoz** [comment]
@agnivade The CircleCI seems to be disabled as #430 states. Probably we will need to wait that one.

**Comment by agnivade** [comment]
Waiting on https://github.com/mattermost/mmctl/pull/445 to be merged. @isacikgoz - this is good to review now.

**Review by isacikgoz — APPROVED** [review]
LGTM, nicely done 👍

**Pull request merged**
