### PR TITLE
[Build] Support go 1.17

### PR DESCRIPTION
**Pull request by roopakv**
#### Summary
Updates mmctl to support go1.17 as described here: https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

This is currently blocking homebrew here: https://github.com/Homebrew/homebrew-core/pull/83413/

#### Ticket Link
https://github.com/mattermost/mmctl/issues/363

### CODE REVIEW

**Comment by roopakv** [comment]
@streamer45 would you be able to take a look at this please.

**Review by streamer45 — APPROVED** [review]
Thank you @roopakv :+1:

**Comment by roopakv** [comment]
awesome. @streamer45 would you also be able to cut a new release after merging this :) 🙏

**Comment by streamer45** [comment]
> awesome. @streamer45 would you also be able to cut a new release after merging this :)

Let me ping someone from our release team and see what we can do about that. /cc @metanerd

**Comment by metanerd** [comment]
Sure thing! I guess releases 5.36 and up are affected by homebrew?

**Comment by metanerd** [comment]
@roopakv Sorry, I have seen this, but I am not sure which release version of mmctl homebrew pulls in. Would you be able to provide me further information please? I can unfortunately not check this on my desktop.

**Comment by roopakv** [comment]
@metanerd right now we pull in 5.38 see [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mmctl.rb#L5)

Once you release a new version we will update to that

**Comment by metanerd** [comment]
@roopakv Ah, I see. Awesome, thank you! I can provide a Patch release after merge.

**Comment by roopakv** [comment]
@metanerd @streamer45 anything i need to do before we can merge? :)

**Comment by metanerd** [comment]
Staying safe and taking care! ;)
Agniva will get to it soon :tm:

**Comment by agnivade** [comment]
Thank you for the PR @roopakv! I guess the problem here is that brew by itself is also doing a gofmt, which is causing the new lines to be added. Go 1.17 is of course fully backwards compatible with the old syntax.

I am wondering if it would be possible for brew to fetch and build from master for the time being until we cut a new release? I am not sure if cutting a new release is justified because the gofmt command from a later release generates some new lines.

This PR is of course good to be merged.

**Review by agnivade — APPROVED** [review]

**Comment by roopakv** [comment]
@agnivade brew has to fetch from a release never master. would really appreciate unblocking go 1.17 for the whole community rather than having to wait for just mmctl. 

you can read more about why brew moves the community forward rather than pin different versions for just a single formuale on the issue linked above.

@agnivade can you also merge the PR? I don't have that ability to do so myself

**Comment by agnivade** [comment]
Thanks @roopakv. Building from 1.17 is fine, and forcing the community to always be on the latest is also okay. But 1.17 was released explicitly on the premise that older build tags will still work. The real issue here is brew is blocked on the gofmt errors which I believe should should not be something that brew should enforce.

Making a patch release to fix a cosmetic issue changes the semantics of a patch release.

That being said, I would defer to @amyblais and @metanerd on this matter.

**Comment by roopakv** [comment]
@agnivade that makes sense and I will work with the brew folks to avoid running gofmt on builds. If you look at the other packages having issues they were forced to upgrade x/sys because of a crash with go 1.17 :) 

However right now I urge mmctl tobreak rules and cut a release :)

**Comment by amyblais** [comment]
Is there anything specific needed from me for this? Does it mean this would get included in a v5.38.2 dot release?

**Comment by metanerd** [comment]
AFAIK nothing specific needed. It will be auto included in the v5.38.2 dot release. I will change the version, so it gets included in server.

**Comment by metanerd** [comment]
@roopakv Thank you for your patience! Would be ready to bump this now: https://github.com/Homebrew/homebrew-core/blob/0c0565210aefb74878d87a8af3736680ea7da6a8/Formula/mmctl.rb#L5

https://github.com/mattermost/mmctl/releases/tag/v5.38.1

**Pull request merged**
