### PR TITLE
[GH13465] Add unit tests to the "ListTeamsCmd" mmctl command

### PR DESCRIPTION
**Pull request by larkox**
#### Summary

Add unit tests to the "ListTeamsCmd" mmctl command
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13465

### CODE REVIEW

**Comment by larkox** [comment]
My reasoning to include the test in this one and not on other tests is that I felt like there was no difference whether the channel was archived or not, and was not being shown to the user whether it was archived or not.

After a deeper thought, it is implicit in the json information (in json you can see the delete_at field with a value over 0), but even though, I wanted to make sure I properly tested both branches.

That being said, if we are offering both representations, shouldn't we be testing both?

**Comment by agnivade** [comment]
> That being said, if we are offering both representations, shouldn't we be testing both?

Sure, we should. But then we should be doing it for all tests as well. But since you have already spent the effort in writing the tests, I don't see any harm in including them. I would just suggest to make the json and plain test variations to be sub-tests of the parent test, since both of them use the same input data. That would reduce some unnecessary boilerplate code.

**Comment by agnivade** [comment]
I apologize for the confusion, but I meant "sub-tests", which would be another level of "s.Run()" inside the parent test.

**Comment by larkox** [comment]
@agnivade Done! Thank you for the feedback!

**Pull request merged**
