### PR TITLE
Add a '  channel users list' command

### PR DESCRIPTION
**Pull request by hmalphettes**
Hi, this command adds the ability to list the users of a channel.
I use it to add the members of a channel to another channel.

```
$ ./mmctl.exe channel users list --help
List users with access to a private channel

Usage:
  mmctl channel users list [channel] [users] [flags]

Examples:
  channel users list myteam:mychannel

Flags:
      --display string   Display the 'username' or 'email' or 'id' of the channel members. (default "email")
```
Thanks for your kind attention!

### CODE REVIEW

**Review by ashishbhate — COMMENTED** [review]
Thanks @hmalphettes! Looking good!

I've added some minor comments inline. Would you be open to writing some end-to-end and unit tests for this feature? Take a look at `channel_users_test.go` and `channel_users_e2e_test`

**Comment by hmalphettes** [comment]
Hi @ashishbhate thanks for the review. Sorry for the belated answer: end of the year break here.
OK, I'll work on your notes and adding the tests. Thanks for the pointers.

**Comment by ashishbhate** [comment]
@hmalphettes no worries, things are slow here as well because of the holidays :) 

Let me know if you need help with anything.

**Comment by jfrerich** [comment]
Hi @hmalphettes!  Just checking in to see if you need any help :)

**Comment by jfrerich** [comment]
Hi @hmalphettes! It would be great to get your PR merged! Please let us know if you will continue or if we should open the PR back up for grabs.

**Comment by emilyacook** [comment]
Hi @hmalphettes! Thank you so much for the contribution. I'm going to go ahead and set this to [stale](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), if you don't think you'll be able to get to it within 30 days just let me know so I can open it back up to the community and link your contribution :)

**Comment by isacikgoz** [comment]
Hey @hmalphettes I'm closing this PR as there is no recent activity. Feel free to ping me of you want to continue working on this!

**Pull request closed without merging**
