### PR TITLE
Add .idea folder to gitignore

### PR DESCRIPTION
**Pull request by lucianomagrao**
#### Summary

Add `.idea` folder to be ignored by git

### CODE REVIEW

**Comment by jfrerich** [comment]
Thanks for the PR, @lucianomagrao!  Was there an associated github issue for this PR?

**Comment by lucianomagrao** [comment]
> Thanks for the PR, @lucianomagrao! Was there an associated github issue for this PR?

No, I was writing some tests and `.idea` popped up on my git status, so I included it on ignore.

**Review by mgdelacroix — APPROVED** [review]
LGTM :+1:

**Review by jfrerich — APPROVED** [review]
Thanks for the catch, @lucianomagrao.

**Pull request merged**
