### PR TITLE
prepare mmctl to next 6.2 release

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- prepare mmctl to next 6.2 release

### CODE REVIEW

**Comment by amyblais** [comment]
Seems some tests are failing.

**Comment by cpanato** [comment]
> Seems some tests are failing.

i will check those, maybe something changed

**Comment by cpanato** [comment]
> Seems some tests are failing.

all good now

**Comment by amyblais** [comment]
@cpanato Do I need to wait for this PR before I cut v6.2.1 Final?

**Comment by cpanato** [comment]
> @cpanato Do I need to wait for this PR before I cut v6.2.1 Final?

yes

**Comment by amyblais** [comment]
@mgdelacroix @isacikgoz Would one of you be able to help review this as a priority?

**Review by isacikgoz — APPROVED** [review]
Seems like we have a flaky test, I just re-run the tests and everything is OK now. LGTM 👍

**Review by mgdelacroix — APPROVED** [review]
LGTM :+1:

**Pull request merged**
