### PR TITLE
Add insecure-skip-verify flag for skip certificate verification

### PR DESCRIPTION
**Pull request by kuai6**
#### Summary

I faced with issues with my local mattermost installation - it can't be managed with mmctl because of self signed certificates.  So i decide to contribute this option to skip tls verification.

Please check it.

### CODE REVIEW

**Comment by noxer** [comment]
@kuai6 unfortunately we can't move forward with the PR until you sign the CLA.

**Comment by isacikgoz** [comment]
@kuai6 let us know if you need additional help with signing the CLA.

**Comment by noxer** [comment]
Closing due to inactivity

**Pull request closed without merging**
