### PR TITLE
[MM-34046] Update server deps

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR updates server deps for `release-5.33` to be in sync. This should fix the reported issue.

cc @amyblais 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34046

### CODE REVIEW

**Comment by amyblais** [comment]
@streamer45 How risky is the fix for a dot release (since there are lot of code changes)? If it would be safer to have this soak for a longer time, let me know.

**Comment by streamer45** [comment]
> @streamer45 How risky is the fix for a dot release (since there are lot of code changes)? If it would be safer to have this soak for a longer time, let me know.

It's all dependencies that are already included in the server release so I'd say it's worth going for a dot release to fix the outstanding issues.

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by streamer45** [comment]
No need to cherry-pick since we are merging directly into the release branch.

**Pull request merged**
