### PR TITLE
Applied correction

### PR DESCRIPTION
**Pull request by cwarnermm**
Documentation correction for: https://github.com/mattermost/docs/pull/5380

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by mgdelacroix** [comment]
@cwarnermm I've ported the change to the code files (and modified the other command accordingly) as those are used as the source of truth to generate the `.rst` files and that was causing the CI to fail.

Changes were done on a04fa66, please take a look and merge if you think they're good!! :)

**Comment by cwarnermm** [comment]
Thanks, @mgdelacroix! The changes on a04fa66 look great. In fact, one of your code changes alerted me to the fact that the docs contain one more error that needs to be corrected (`mmctl team users remove`) due to `users` missing in the example. Addressed that issue via https://github.com/mattermost/docs/pull/5383

**Comment by cwarnermm** [comment]
Thank you, @mgdelacroix, for ported the change to the code files! Really appreciate the help on this one!

**Comment by noxer** [comment]
What is missing for this PR to be merged or closed?

**Comment by cwarnermm** [comment]
@noxer I noticed that the **Files changed** tab contains 0 entries. If I were to merge this PR, I'm not 100% clear on what would happen, if anything. Thoughts?

**Comment by noxer** [comment]
I think that means the changes are already in the codebase. I guess nothing would happen.

**Comment by cwarnermm** [comment]
Thanks, @noxer. @mgdelacroix applied the changes via a specific commit, so I agree that we're likely okay to simply merge or close this PR. I'll merge it.

**Pull request merged**
