### PR TITLE
Update channel example for consistency

### PR DESCRIPTION
**Pull request by mgdelacroix**

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by cwarnermm — APPROVED** [review]
Thank you!

**Comment by justinegeffen** [comment]
@mgdelacroix, is this good to merge? :)

**Comment by mgdelacroix** [comment]
Yes! Will do right now, thanks for being on top of it @justinegeffen!

**Comment by justinegeffen** [comment]
Thank you, @mgdelacroix!

**Pull request merged**
