### PR TITLE
deprecate --format flag

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Deprecated the `--format` flag, we already use `plain` format for default so there is no need for a string format flag. The flag will be around to be used anyway.

#### Release notes
```release-note
--format flag has been deprecated, if you want json output please use --json instead of --format=json
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :robot: 

Exciting times ahead :D

**Review by lindy65 — APPROVED** [review]
Thanks @isacikgoz - I'll test this after merge 👍 

Can you link me to the Jira ticket for this PR please?

**Comment by isacikgoz** [comment]
Hey @lindy65 here I created the ticket, we were using FB for the issue tracking 😅 

https://mattermost.atlassian.net/browse/MM-38032

**Comment by lindy65** [comment]
Thanks @isacikgoz 👍

**Pull request merged**
