### PR TITLE
Add .gitpod.yml

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

[Open in Gitpod](https://gitpod.io/#https://github.com/mattermost/mmctl/pull/615)

### CODE REVIEW

**Comment by mickmister** [comment]
@isacikgoz I get this error when running `make build` in the Gitpod workspace:

```
mattermost-govet is not installed. Please install it executing "GO111MODULE=off go get -u github.com/mattermost/mattermost-govet"
```

Running that command doesn't fix the problem either. Any ideas why this may happen?

**Comment by isacikgoz** [comment]
@mickmister I don't know how gitpod works but do you mean that you are getting the same error after installing `mattermost-govet`? If so, I think $GOPATH is not added to $PATH hence the binary is not being recognized.

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
Thank you for your contribution. :+1:  `mmctl` has been moved into https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl.  Please resubmit your PR to https://github.com/mattermost/mattermost.

**Pull request closed without merging**
