### PR TITLE
Add installation method in README to introduce single binary option

### PR DESCRIPTION
**Pull request by flat35hd99**
#### Summary

Add single binary option of installation.

### CODE REVIEW

**Comment by flat35hd99** [comment]
My collegue ask me "How to install this in our linux machine?" and I realized that people who don't know Golang also don't know installation method of software written Golang.

I believe that this message helps a lot of people who _use_ technology.

**Comment by flat35hd99** [comment]
/check-cla




2022年11月17日(木) 16:26 Mattermod ***@***.***>:

**Comment by hanzei** [comment]
Thank you for your contribution. :+1:  `mmctl` has been moved into https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl.  Please resubmit your PR to https://github.com/mattermost/mattermost.

**Pull request closed without merging**
