### PR TITLE
Add a new command to upload a license from a license payload string

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
This command allows uploading a license from a license payload string. We'll need this in Cloud for some upcoming plan change optimizations.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46000

### CODE REVIEW

**Comment by nickmisasi** [comment]
@cwarnermm I'm not sure this one will be super useful for end users. I've added documentation for it nonetheless, but if you think we should just not document it, let me know and I can remove it.

**Comment by cwarnermm** [comment]
Thanks, @nickmisasi! The Mattermost Product Documentation includes all available mmctl commands, so this is great to have on my radar.

**Review by agnivade — APPROVED** [review]
oops sorry I thought I approved this

**Review by cwarnermm — APPROVED** [review]

**Review by gabrieljackson — APPROVED** [review]
LGTM

**Pull request merged**
