### PR TITLE
[MM-29808] Add e2e test for botDisableCmdF

### PR DESCRIPTION
**Pull request by wijayaerick**
#### Summary

Added e2e test for botDisableCmdF

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16004

JIRA: https://mattermost.atlassian.net/browse/MM-29808

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
Amazing job @wijayaerick, LGTM!! :+1:

**Review by ethervoid — APPROVED** [review]
LGTM! Thanks for the contribution

**Review by lindy65 — APPROVED** [review]
Thanks @wijayaerick @mgdelacroix - looks good to me 👍

**Pull request merged**
