### PR TITLE
[MM-29809] Add end-2-end tests to bot assign command

### PR DESCRIPTION
**Pull request by lucianomagrao**
#### Summary

Add e2e tests to `mmctl bot assign` command.

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/16005
JIRA: https://mattermost.atlassian.net/browse/MM-29809

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM!

**Review by isacikgoz — COMMENTED** [review]
Thanks for your contribution @lucianomagrao 🚀 Looks good to me, have a couple of minor points.

**Comment by jfrerich** [comment]
@isacikgoz there was another commit since your last review. Would you mind re-reviewing? Thanks!

**Review by isacikgoz — APPROVED** [review]
Sorry, this totally escaped from me! Looks good to go 🚀 Thanks @lucianomagrao

**Review by lindy65 — APPROVED** [review]
Thanks @lucianomagrao @isacikgoz - looks good to me 👍

**Comment by hanzei** [comment]
Thank you very much for the contribution @lucianomagrao :tada:

**Pull request merged**
