### PR TITLE
Adds export e2e test ids

### PR DESCRIPTION
**Pull request by mgdelacroix**
Adds test ids for export command e2e tests

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @mgdelacroix - apologies for missing out the Zephyr (TM4J) test keys for the `TestExportListCmdF` tests!  Here they are :)

- TestExportListCmdF | some exports - MM-T3912
- TestExportListCmdF | no exports - MM-T3913
- TestExportListCmdF | no permissions - MM-T3914

Let me know once you've added them and I'll re-review this PR :)  Thanks!

**Comment by mgdelacroix** [comment]
Thanks a lot @lindy65!! Added those ids, PTAL :)

**Review by lindy65 — APPROVED** [review]
Looks good to me 👍 Thanks :)

**Review by streamer45 — APPROVED** [review]
Nice, thanks :+1:

**Pull request merged**
